<?xml version="1.0" encoding="utf-8"?><Database Name="TP-VD" Class="LinQDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=FAV15SRV01\SOPIPING;Initial Catalog=TP-VD;Integrated Security=True" SettingsObjectName="Administrador_de_entradas_para_la_Superliga.Properties.Settings" SettingsPropertyName="TP_VDConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Billet" Member="Billet">
    <Type Name="Billet">
      <Column Name="int" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="numSocio" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="idPlace" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idMatch" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Socios_Billet" Member="Socios" ThisKey="numSocio" OtherKey="numSocio" Type="Socios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Match" Member="Match">
    <Type Name="Match">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="intitule" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="coefMatch" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Socios" Member="Socios">
    <Type Name="Socios">
      <Column Name="numSocio" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nom" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="prenom" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="adresse" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="codePostal" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="telephone" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="mdp" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Socios_Billet" Member="Billet" ThisKey="numSocio" OtherKey="numSocio" Type="Billet" />
    </Type>
  </Table>
  <Table Name="dbo.Tribunes" Member="Tribunes">
    <Type Name="Tribunes">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nom" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="capacite" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="prix" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>